# Compiles Typst into a PDF and publishes it automatically
name: Compile Typst

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Typst
        uses: typst-community/setup-typst@v3.1.0            

      - name: Compile to PDF
        run: typst compile main.typ "A Practical Guide to Protein Redesign.pdf"

      - name: Generate Release Tag
        id: generate_release_tag
        uses: amitsingh-007/next-release-tag@v6.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: 'v'
          tag_template: 'yyyy.mm.dd.i'

      - name: Publish PDFs in Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.generate_release_tag.outputs.next_release_tag }}
          files: "*.pdf"
